### ISSUE TITLE
VIDEOIO(cvCreateFileCapture_AVFoundation (filename)): raised unknown C++ exception!

### ISSUE THREAD

**Issue by fouadkada** [openpnp/opencv#19]
Hey,

I am facing the following issue with VideoCapture.open(url)
`VIDEOIO(cvCreateFileCapture_AVFoundation (filename)): raised unknown C++ exception!`

when I built opencv using cmake and then make and then make install that problem was not there.
only when i switched to using maven that this problem appeared.

what might be the issue?

**Comment by vonnieda** [comment]
What version of OS X are you running?

**Comment by fouadkada** [comment]
I'm on el capitan 10.11.6

**Comment by vonnieda** [comment]
What type of file are you trying to open? If you can post an example file that displays the behavior somewhere online that will be helpful.

**Comment by fouadkada** [comment]
I am trying to open an rtsp url.
something more or less like the following:

```
VideoCapture capture = new VideoCapture();
capture.open("rtsp://192.168.2.208:1935/vod/sample-3.m4v");
if (capture.isOpened()) {
// some code here
}
```

the rtsp url comes from a wowza server running locally.
when i use the opencv 3.2.0 built manually everything works as expected.

Do you think this would cause issues on other architectures? because I am planning on running this code on an amazon ec2 instance running amazon linux

**Comment by vonnieda** [comment]
It will depend a lot on which codecs are compiled in to the build, and may depend on if the required codecs are installed on the target machine. I suggest you distribute your own build of opencv with your application to be sure. This package does not include very many codecs as it's primary purpose is machine vision, not video decoding. I suspect that the error you are getting is due to ffmpeg not being included in this build.

**Comment by fouadkada** [comment]
I am sure that what I need requires ffmpeg, how can I create a PR that has ffmpeg included since I am really interested in the convenience of maven

**Comment by vonnieda** [comment]
See https://github.com/openpnp/opencv/blob/develop/RELEASE.md for the instructions that I follow when building a release. If you can update that with information about how to build with ffmpeg (and other required dependencies) then I will do a new release based on that. You may also want to take a look at https://github.com/openpnp/opencv/issues/13 since it is also a request for more included libraries.

One thing I am not sure about, and maybe you can look into, is whether we need to distribute the ffmpeg binaries with the library, or if they can be statically linked. I vaguely remember there being some kind of licensing issue with distributing ffmpeg, so we need to be aware of that as well.

**Comment by vonnieda** [comment]
I've decided not to include ffmpeg in this distribution. It's difficult enough to keep up with releases of OpenCV itself - adding other artifacts just isn't going to happen.
