### ISSUE TITLE
OpenJDK 64-Bit Server VM warning - EC2 war file

### ISSUE THREAD

**Issue by rajesh-rt** [openpnp/opencv#21]
Hello,

I have added maven dependency in a servlet, generated a war file and deployed it on tomcat running in AWS EC2 instance. I loaded the library by calling:  **nu.pattern.OpenCV.loadShared();**

But I'm getting the following warning at the time loading the shared library.

OpenJDK 64-Bit Server VM warning: You have loaded library /var/cache/tomcat8/temp/opencv_openpnp8944603593498400654/nu/pattern/opencv/linux/x86_64/libopencv_java320.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

When I deploy the war to my local instance of tomcat, its working perfectly.
I want to use the library for detecting and cropping faces in image using haarcascade classifiers.

**Comment by vonnieda** [comment]
This warning can be pretty much ignored. See https://groups.google.com/forum/#!topic/fusionreactor/iRsnTT3al04. If it concerns you, I would welcome a pull request to fix the build process.

**Comment by sinusee** [comment]
I got the following warning:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by nu.pattern.OpenCV$SharedLoader (file:/home/martin/.m2/repository/org/openpnp/opencv/3.2.0-0/opencv-3.2.0-0.jar) to field java.lang.ClassLoader.usr_paths
WARNING: Please consider reporting this to the maintainers of nu.pattern.OpenCV$SharedLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /tmp/opencv_openpnp6598848942071423284/nu/pattern/opencv/linux/x86_64/libopencv_java320.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
the full question related to this problem is in https://stackoverflow.com/questions/49298293/warning-an-illegal-reflective-access-operation-has-occurred-portable-opencv-in

**Comment by wtsiamruk** [comment]
The warning is still present in 2020

**Comment by charlesritchea** [comment]
I'm pretty sure this will become more than a warning in Java 17 which is right around the corner and LTS

**Comment by wtsiamruk** [comment]
Right...

**Comment by wtsiamruk** [comment]
@vonnieda could you give a little more details of what should be fixed in the build process?
