### ISSUE TITLE
UnsatisfiedLinkError: opencv_java342.dll: Can't find dependent libraries (Windows Server 2012R2)

### ISSUE THREAD

**Issue by fgrebe** [openpnp/opencv#43]
### Describe the Issue
With version 3.4.2-1 I'm getting a UnsatisfiedLinkError.
In my code I have tried `OpenCV.loadShared();` and `OpenCV.loadLocally();`

Note that it is working fine on a Windows 8.1 but on Windows Server 2012 R2 (x64) the exception occurs, probably due to some libraries that are not present ona server system, similar to the ffmpeg bug(?).

Java version is 1.8.0_191.
### Steps to Reproduce
Occurs every time when starting the java application using opencv version 3.4.2-1.
### Notes, Log Files, etc. to Show the Issue
```
Caused by: java.lang.UnsatisfiedLinkError: C:\...\AppData\Local\Temp\opencv_openpnp5624012180889590870\nu\pattern\opencv\windows\x86_64\opencv_java342.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(Unknown Source)
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at nu.pattern.OpenCV$LocalLoader.<init>(OpenCV.java:297)
	at nu.pattern.OpenCV$LocalLoader.<init>(OpenCV.java:293)
	at nu.pattern.OpenCV$LocalLoader$Holder.<clinit>(OpenCV.java:303)
	at nu.pattern.OpenCV$LocalLoader.getInstance(OpenCV.java:307)
	at nu.pattern.OpenCV.loadLocally(OpenCV.java:290)
	... 86 more
```

_Edit:_ The missing dlls (left: Win 8.1; right: Win Server):
![dependencies](https://user-images.githubusercontent.com/3875910/51183475-97788400-18d1-11e9-8689-131f81dfb260.PNG)

_Edit 2_: Apparently the **Media Feature Pack for N and KN versions** is needed. Just wondering if this dependency is something you plan to "fix"/remove or if I should look for another workaround?

**Comment by vonnieda** [comment]
Hi @fgrebe, does installing the Media Feature Pack resolve the issue? Or is that not an option for you?

**Comment by fgrebe** [comment]
Hi, unfortunately that's not an option in our configuration/setup.

**Comment by vonnieda** [comment]
Hi @fgrebe,

I don't have any current plans to remove this dependency. Due to the complexity of building OpenCV on Windows, I don't actually build the binaries myself - I just use the prebuilt ones from the OpenCV distribution. For me to remove this dependency I'd have to build it myself as part of the release process and that's quite a bit of work.

If this is important to you, or others, please consider researching what would be involved in producing an equivalent binary and whether or not there are ramifications of removing the dependency. As a guess, I would bet that it relies on that for video capture and video decoding.

In addition, it appears others have run into this problem and have found a solution by installing the required pack: https://jakubmertl.com/blog/python-import-cv2-error

I'll leave this open for now in case others want to discuss a solution.

Thanks,
Jason

**Comment by fgrebe** [comment]
Thanks for the clarification. 
We already had the feeling that we would have to build it ourselves to get rid of the dependency.
Should I have any new information on how to build the binaries myself I'll share it here.

**Comment by vonnieda** [comment]
Closing as won't fix. Please feel free to reopen is a fix is found.
