### ISSUE TITLE
Facial Recognition using Fisher Faces..?

### ISSUE THREAD

**Issue by josephincture** [openpnp/opencv#62]
Does this have support Facial Recogntion using Fisher faces?

**Comment by ian-arkver** [comment]
This is a set of Java bindings for upstream OpenCV maintained for the openPnP community. Since it pulls in the upstream OpenCV jar, it should support everything that's in that, which as of at least version 4.3.0 seems to include some support for Fisher faces:
https://docs.opencv.org/4.3.0/da/d60/tutorial_face_main.html

Face recognition is obviously not used for openPnP, so your question would probably be better directed to the upstream OpenCV community.
